"""Service wiring. Built once at app startup from configs/active."""

from dataclasses import dataclass

from app.paths import data_dir, logs_dir
from app.services.config_service import load_config
from app.services.signal_service import SignalService
from engines.scoring import ScoringStub
from execution.paper_broker import PaperBroker
from risk.economic_calendar import load_artifact as load_calendar_artifact
from risk.risk_engine import RiskEngine


@dataclass
class ServiceContainer:
    signal_service: SignalService
    risk_engine: RiskEngine
    broker: PaperBroker
    mode: str
    risk_config: dict
    watchlist: list[str]


def build_services() -> ServiceContainer:
    risk_config = load_config("risk")
    autonomy = load_config("autonomy")
    watchlist_config = load_config("watchlist")
    scoring_config = load_config("scoring")

    mode = str(autonomy.get("mode", "paper"))
    if mode != "paper":
        # Hard safety gate: Milestone 1 has no live code path and refuses to start otherwise.
        raise RuntimeError(
            f"autonomy.yaml mode is '{mode}' but only 'paper' is supported in Milestone 1"
        )

    logs = logs_dir()
    broker = PaperBroker(
        logs, starting_capital=float(risk_config.get("starting_capital", 10000))
    )
    # Static risk.yaml entries plus windows generated by risk.economic_calendar
    # (refresh with: python -m risk.economic_calendar).
    risk_config = dict(risk_config)
    risk_config["event_blackout_calendar"] = list(
        risk_config.get("event_blackout_calendar") or []
    ) + load_calendar_artifact()
    risk_engine = RiskEngine(risk_config, mode=mode)
    scorer = ScoringStub(scoring_config)
    watchlist = list(watchlist_config.get("pairs", []))
    signal_service = SignalService(
        logs_dir=logs,
        risk_engine=risk_engine,
        broker=broker,
        scorer=scorer,
        watchlist=watchlist,
        mode=mode,
        artifacts_dir=data_dir() / "artifacts",
    )
    return ServiceContainer(
        signal_service=signal_service,
        risk_engine=risk_engine,
        broker=broker,
        mode=mode,
        risk_config=risk_config,
        watchlist=watchlist,
    )
